# Generated by Django 4.2.4 on 2023-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articlestatus',
            field=models.CharField(default='draft', max_length=100),
        ),
    ]
