# Generated by Django 4.2.4 on 2023-09-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_isrejected_article_isreviewd'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
