# Generated by Django 4.2.4 on 2023-09-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleSubTitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
